name: build-executables
run-name: Generating executables for ${{github.ref_name}}
on:
  push:
    branches:
      - main
jobs:
  generate-executables:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
          cache: 'pip'
      # Build python script into a stand-alone exe
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - uses: Nuitka/Nuitka-Action@main
        with:
          script-name: lexecution.py
          standalone: true
          disable-console: true
          onefile: false
          enable-plugins: pyside6

      # Uploads artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: lexecution.exe
          path: build/lexecution.exe
